### ISSUE TITLE
login_params

### ISSUE THREAD

**Issue by odlan** [Kenshii/500px-Bot#1]
Hello, first I want say thank you for your work. The bot works very well. 
I wanna put my login params inside the 500px.py so I can use it in cronjob whitout my interaction an then I have modded your script as follow

`login_params = {`
    `'authenticity_token': '',`
    `'session[email]': "myemail@email.com",`
    `'session[password]': "mypassword"`

but when I start the script I recevied this message in console 

`Retrieved login page.`
`A server error (422) occured. Retrying...`
`Error page: https://api.500px.com/v1/session`

If I use my login params in the original script as my input that works flawless
Can you help me?

Thank's

**Comment by shane-tw** [comment]
That sounds odd. Can you double-check your email and password are correct?

**Comment by odlan** [comment]
Thank you for you reply.
I have solved with single quote in login params
Have a nice day

2016-08-08 14:20 GMT+02:00 Shane O Donovan notifications@github.com:
