### ISSUE TITLE
Just unfollow users

### ISSUE THREAD

**Issue by jlntrt** [Kenshii/500px-Bot#13]
In short words: What do you think about an option to unfollow all users that the script added?

In case you want to stop using the bot, there no way to unfollow all these users (beside removing them manually).

Thank you so far :slightly_smiling_face:

**Comment by mactrash** [comment]
After couple days of using, I think I need this feature too.

**Comment by shane-tw** [comment]
https://gist.github.com/Kenshii/a9e790ada901cad5083bf252c5fd3a72  
It's untested but it should work. Let me know.
