### ISSUE TITLE
Unfollowers

### ISSUE THREAD

**Issue by AlanJereb** [Kenshii/500px-Bot#14]
Hello,

Would it be possible that from time to time the script checks which users unfollowed you and unfollows them? Right now it unfollows just those who didn't follow you back. 

Thank you!

**Comment by shane-tw** [comment]
If:

1.  Someone isn't following you; and
2.  You followed them more than 24 hours ago, or followed them manually without the bot

The script will unfollow them.

Hopefully that does what you were looking for.
