### ISSUE TITLE
500px | Warning (spam detection)

### ISSUE THREAD

**Issue by gnesher** [Kenshii/500px-Bot#18]
Hi,
I've been running the bot for about a month (love it by the way) and got an email today with the following message:
`This email is a warning that we have found spam comments or links being posted from your account. Advertising and links are not permitted on 500px. This includes advertising third party services, and soliciting views or votes from other users.

This behavior is not inline with our community's guidelines. If it continues, your account will be banned. If you have any questions, contact us at help@500px.com.

Thanks,
500px
`

Anyone got that before? anything we can do about it? I assume I need to shut down the bot?

**Comment by shane-tw** [comment]
Not much you can do that. At least it's a warning and not a ban.  
You could try reducing the number of follows per day from 101 to something lower, but you'd still be taking a risk.

Safest bet would be to stop using the bot.
