### ISSUE TITLE
https://api.500px.com/v1/session 422

### ISSUE THREAD

**Issue by mactrash** [Kenshii/500px-Bot#23]
{"error":"Not found","status":404}

**Comment by shane-tw** [comment]
I only get this issue if I manually load https://api.500px.com/v1/session in the browser.  
The server responds to POST requests, but not GET requests, hence why this happens in the browser.

**Comment by mactrash** [comment]
![screen shot 2017-06-28 at 1 46 00 pm](https://user-images.githubusercontent.com/1506388/27622207-3a9ec668-5c08-11e7-8b78-ad7102bc3dc4.png)
it show up in the log thats why I paste to the browser, please check. @Kenshii

**Comment by shane-tw** [comment]
Have you tried logging in manually (in browser) since getting that error?  
I just ran the bot on my own account just now and it logged in fine, so I'm not sure what the issue could be.

**Comment by mactrash** [comment]
Thanks for your hit... I have changed email, and not update the script... sorry @Kenshii
