### ISSUE TITLE
Script runs but gives - "A server error (422) occured. Retrying..."

### ISSUE THREAD

**Issue by ademcfade** [Kenshii/500px-Bot#27]
Hi

I've just been trying to run the script and getting time outs - just wondering if they've changed the API or whether anyone else is getting this issue

Here's the output

C:\Users\New User>"C:\Users\New User\AppData\Local\Programs\Python\Python36-32\python.exe"  "C:\500px\500px-Bot-master\500px.py"
19:18:22 - Retrieved login page.
19:18:43 - A server error (422) occured. Retrying...
19:18:43 - Error page: https://api.500px.com/v1/session
19:18:48 - Web page timed out. Retrying...

**Comment by shane-tw** [comment]
The only other person who has reported this issue entered their details incorrectly.
Can you verify that you've changed the details in 500px.py to the correct details?
https://github.com/shanepm/500px-Bot/issues/23#issuecomment-311604422

**Comment by ademcfade** [comment]
ah I'm such an idiot - seen the issue - thanks for the prompt reply and I love what your script does :-)
