### ISSUE TITLE
 Retrieved login page.

### ISSUE THREAD

**Issue by DimitarGanchev** [Kenshii/500px-Bot#30]
10:12:53 - Retrieved login page.
10:13:14 - A server error (422) occured. Retrying...
10:13:14 - Error page: https://api.500px.com/v1/session
10:13:20 - A server error (422) occured. Retrying...
10:13:20 - Error page: https://api.500px.com/v1/session
10:13:26 - A server error (422) occured. Retrying...
10:13:26 - Error page: https://api.500px.com/v1/session
10:13:31 - A server error (422) occured. Retrying...
10:13:31 - Error page: https://api.500px.com/v1/session

thats what ive got as a issue any suggestion ?

**Comment by faycalmarjane** [comment]
I have the same issue :(

**Comment by shane-tw** [comment]
Have you [read this](https://github.com/shanepm/500px-Bot/issues/27)?
If yes and you're still getting it then I'll reopen it but I'm busy lately and I've honestly lost interest in this so I wouldn't expect a fix any time soon if this is actually an issue.
