### ISSUE TITLE
Endless loop, if a user account isn't available any longer

### ISSUE THREAD

**Issue by hometm** [Kenshii/500px-Bot#7]
The 500px-Bot sometimes picks a user account, that isn't valid. In this case, the Bot is running a endless loop. 

(for the following listing I anonymized the user name, but with this anonymized user name the problem can be reproduced)

14:56 - A server error (404) occured. Retrying...
14:56 - Error page: https://500px.com/a___/follow
14:56 - A server error (404) occured. Retrying...
14:56 - Error page: https://500px.com/a___/follow
14:56 - A server error (404) occured. Retrying...
14:56 - Error page: https://500px.com/a___/follow 

If I try to access to https://500px.com/a___/follow a n error page is displayed. The error page says 'no such page'.

I guess, that this error occurs if a user deletes its account, after uploading images.

Is it possible to skip such user accounts?

**Comment by shane-tw** [comment]
Thanks, should be fixed. Let me know if you encounter any more issues.
