### ISSUE TITLE
can't load the script

### ISSUE THREAD

**Issue by 8solo5giuls** [Kenshii/500px-Bot#8]
Is that normal?

MBPG:500px-Bot-master Pino$ python 500px.py 
Traceback (most recent call last):
  File "500px.py", line 3, in <module>
    import requests, time, json, os
ImportError: No module named requests

**Comment by shane-tw** [comment]
It's normal. You need to install the dependencies.
`pip install requests`

**Comment by Kenshii** [comment]
In particular, see https://github.com/Kenshii/Dribbble-Bot/issues/1

**Comment by Charly47290** [comment]
Hi Kenshii !
Thanks a lot for the program.
Sorry to ask for help but I know nothing about programing.
I opened the file in text edit and added my mail and password (and no authenticity token?) and then I got this 

macbook-pro:~ charly$ cd '/Users/charly/Downloads/500px-Bot-master/' && '/usr/bin/pythonw'  '/Users/charly/Downloads/500px-Bot-master/500px.py'  && echo Exit status: $? && exit 1
  File "/Users/charly/Downloads/500px-Bot-master/500px.py", line 28
SyntaxError: Non-ASCII character '\xe2' in file /Users/charly/Downloads/500px-Bot-master/500px.py on line 28, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
macbook-pro:500px-Bot-master charly$ 1201
-bash: 1201: command not found
macbook-pro:500px-Bot-master charly$ 

Thank you very much for any help
