### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Charly47290** [Kenshii/500px-Bot#9]
Hi Kenshii !
Thanks a lot for the program.
Sorry to ask for help but I know nothing about programing.
I opened the file in text edit and added my mail and password (and no authenticity token?) and then I got this

macbook-pro:~ charly$ cd '/Users/charly/Downloads/500px-Bot-master/' && '/usr/bin/pythonw' '/Users/charly/Downloads/500px-Bot-master/500px.py' && echo Exit status: $? && exit 1
File "/Users/charly/Downloads/500px-Bot-master/500px.py", line 28
SyntaxError: Non-ASCII character '\xe2' in file /Users/charly/Downloads/500px-Bot-master/500px.py on line 28, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
macbook-pro:500px-Bot-master charly$ 1201
-bash: 1201: command not found
macbook-pro:500px-Bot-master charly$

Thank you very much for any help

**Comment by shane-tw** [comment]
The code on GitHub doesn't have this issue.
It must have happened when you added your email address.
Check to ensure that there aren't any symbols near line 28 (the email).
Inside the single quotation marks, you should put your email and password.
authentication_token should be left blank.
